# site settings
title: Portfolio and CV
subtitle: Christopher Oldham
email: coldham10@gmail.com
description: A CV and project portfolio site
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://coldham10.github.io" # the base hostname & protocol for your site
author: Christopher Oldham
street_address:
city: London
state:
zip_code:
country: United Kingdom
phone: +44 7599 842414

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url: https://github.com/coldham10
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/coldham10/
pinterest_url:
slack_url:
twitter_url:

#formspree
formspreehash: xnqogrny

# build settings
markdown: kramdown

sass:
  style: compressed
